deregenboog/ecd

- app/controllers/iz_hulpaanbiedingen_controller.php
- app/controllers/iz_hulpvragen_controller.php
- app/views/iz_hulpaanbiedingen/download.twig
- app/views/iz_hulpaanbiedingen/index.twig
- app/views/iz_hulpvragen/download.twig
- app/views/iz_hulpvragen/index.twig
- src/IzBundle/Form/IzHulpaanbodFilterType.php
- src/IzBundle/Form/IzHulpvraagFilterType.php
> adds download buttons to iz hulpvragen & hulpaanbiedingen index

- app/Resources/views/login.html.twig
- app/config/config.yml
- app/config/parameters.yml.dist
- app/config/version.yml
Laatste dingen + version bump.
> Version bump, last things.

- src/AppBundle/Doctrine/MysqlDateType.php
- src/AppBundle/Service/KlantDao.php
- src/IzBundle/Repository/IzKlantRepository.php
- src/IzBundle/Repository/IzVrijwilligerRepository.php
adapted convertToPhpValue method to reflect this change too.
> Removed all 0000-00-00 dates and changed to 1970-01-01.

- src/AppBundle/DataFixtures/ORM/fixtures.yml
- src/DagbestedingBundle/Controller/TrajectcoachesController.php
- src/DagbestedingBundle/DataFixtures/ORM/fixtures.yml
- src/DagbestedingBundle/Form/TrajectFilterType.php
- src/DagbestedingBundle/Form/TrajectType.php
- src/DagbestedingBundle/Form/TrajectcoachType.php
- src/DagbestedingBundle/Resources/views/trajectcoaches/delete.html.twig
- src/DagbestedingBundle/Resources/views/trajectcoaches/index.html.twig
- tests/DagbestedingBundle/Controller/TrajectcoachesControllerTest.php
> Fix trajectcoach filter/sorting/delete

- src/OekraineBundle/Resources/views/bezoekers/view.html.twig
> Remove dead link

- app/DoctrineMigrations/2022/Version20221212102839.php
- src/AppBundle/Entity/Klant.php
- src/AppBundle/Form/KlantType.php
- src/AppBundle/Resources/views/klanten/_form.html.twig
- src/AppBundle/Resources/views/klanten/add.html.twig
- src/AppBundle/Resources/views/klanten/edit.html.twig
- src/AppBundle/Resources/views/klanten/view.html.twig
- src/MwBundle/Resources/views/klanten/view.html.twig
- templates/klant_basis.html.twig
> Voorkeurstaal en overige talen toevoegen

- src/MwBundle/Resources/views/klanten/view.html.twig
> Dossier als eerste tabblad

- src/MwBundle/Filter/KlantFilter.php
- src/MwBundle/Form/KlantFilterType.php
- src/MwBundle/Resources/views/klanten/index.html.twig
> Aanpassingen MW klant-dossier

- src/TwBundle/Report/Afsluitingen.php
- src/TwBundle/Resources/config/reports.yml
- src/TwBundle/Service/HuurovereenkomstAfsluitingDao.php
- src/TwBundle/Service/HuurovereenkomstAfsluitingDaoInterface.php
> Rapportage toevoegen: afsluitredenen huurovereenkomst per project

- src/TwBundle/Resources/config/exports.yml
> Afsluitreden koppeling toevoegen aan export

- src/TwBundle/Filter/KlantFilter.php
- src/TwBundle/Filter/VerhuurderFilter.php
- src/TwBundle/Form/KlantFilterType.php
- src/TwBundle/Form/VerhuurderFilterType.php
- src/TwBundle/Resources/views/klanten/index.html.twig
- src/TwBundle/Resources/views/verhuurders/index.html.twig
Closes #1343 
Checkbox vervangen door dropdown met actief/niet-actief. Toegepast op klanten en verhuurders, niet op verzoeken, aanbiedingen, koppelingen.
> Aanpassen filter actief/niet-actief

- src/VillaBundle/Resources/config/services.yml
Closes #1335 
DI-configuratie fout: VrijwilligersController kreeg export service uit MW-bundle.
> Fix Villa downloads

- src/AppBundle/Service/KlantDao.php
> Ook partner link weghalen bij verwijderen klant.

- src/AppBundle/Twig/EcdRoutingExtension.php
- templates/add.html.twig
- templates/delete.html.twig
- templates/edit.html.twig
> Add route_exists Twig functino

- src/TwBundle/Resources/views/klanten/view.html.twig
> #1430 inkomenverklaring zichtbaar.

- public/assets/css/regenboog-bootstrap.css
- src/TwBundle/Filter/KlantFilter.php
- src/TwBundle/Form/KlantFilterType.php
- src/TwBundle/Resources/views/klanten/index.html.twig
- templates/html.macro.twig
> #1432 filteren op medewerker + filter snelkoppelingen.

- src/TwBundle/Form/KlantFilterType.php
> #1386 naam gekoppeld filter optie onbekend tw aangepast.

- app/DoctrineMigrations/2023/Version20230407121019.php
- config/sql_reports/repatrieringen_per_klant.sql
- src/MwBundle/Controller/KlantenController.php
- src/MwBundle/Entity/Afsluiting.php
- src/MwBundle/Form/AfsluitingType.php
- src/MwBundle/Resources/views/klanten/_mw.html.twig
- src/MwBundle/Resources/views/klanten/close.html.twig
- src/MwBundle/Resources/views/klanten/edit_mw_dossier_status.html.twig
- src/MwBundle/Resources/views/klanten/view.html.twig
> #1249 repatrieringen extra gevens in afsluiting en rapportage per klant.

- src/InloopBundle/Controller/VerslagenController.php
- src/InloopBundle/Resources/views/klanten/view.html.twig
- src/InloopBundle/Resources/views/verslagen/add.html.twig
fix inloopverslagen.  Lekker veel duplicate code :(
> Inloop verslagen stuk :(

- src/MwBundle/Report/AMW.php
- src/MwBundle/Report/AbstractMwReport.php
- src/MwBundle/Report/Amstelland.php
- src/MwBundle/Report/BegeleidThuis.php
- src/MwBundle/Report/CaseloadMedewerkers.php
- src/MwBundle/Report/STED.php
- src/MwBundle/Resources/config/reports.yml
- src/MwBundle/Service/VerslagDao.php
Fixes #1593 and #1591 caseload rapportage en gezinnen in amstelland.
> Aanpassingen MW Rapportages.

- src/MwBundle/Report/AbstractMwReport.php
- src/MwBundle/Service/MwDossierStatusDao.php
- src/MwBundle/Service/VerslagDao.php
> Fix verschil in rapportage aantallen oud en nieuw voor MW.

- Dockerfile.test
- docker/php/Dockerfile
- src/AppBundle/Controller/AbstractRapportagesController.php
- src/DagbestedingBundle/Form/MedewerkerType.php
- src/GaBundle/Form/EmailMessageType.php
- src/HsBundle/Event/FactuurSubscriber.php
- src/HsBundle/Event/KlantUpdater.php
- src/IzBundle/Event/IntakeEventSubscriber.php
- src/OekBundle/Event/DeelnemerEventSubscriber.php
- src/OekBundle/Form/EmailMessageType.php
- src/ScipBundle/Event/DeelnemerEventSubscriber.php
- src/TwBundle/Form/MedewerkerType.php
- tests/GaBundle/Controller/RapportagesControllerTest.php
- tests/HsBundle/Controller/RapportagesControllerTest.php
- tests/OekBundle/Controller/RapportagesControllerTest.php
De directe deprecation warnings zijn opgelost in deze PR. Er zijn nog wel "Remaining indirect deprecation notices", maar die moeten opgelost worden in de betreffende libraries.
> Fix deprecation warnings

- .github/workflows/ci.yaml
- Makefile
- composer.json
- composer.lock
- src/Kernel.php
- templates/inloop/intakes/view.pdf.twig
- templates/oekraine/intakes/view.pdf.twig
Linting toegevoegd aan de CI-pipeline en een paar foutjes hersteld om de build te laten slagen. Hier kunnen we tzt bv ook checks op code standards and code complexity toevoegen.
> Add linting (code, templates, code, service-container) to CI pipeline

- .github/workflows/ci.yaml
- src/AppBundle/Controller/AbstractController.php
- src/AppBundle/Twig/AppExtension.php
- src/ClipBundle/Filter/VraagFilter.php
- src/DagbestedingBundle/Controller/DeelnamesController.php
- src/InloopBundle/Controller/LocatiesController.php
- src/InloopBundle/Controller/RegistratiesController.php
Hiermee worden de tests en checks zowel met PHP 7.4 als 8.1 gedaan, ivm de aanstaande upgrade naar 8.1
> Setup PHP version matrix

- src/InloopBundle/Service/AccessUpdater.php
- src/InloopBundle/Strategy/AmocStrategy.php
- src/InloopBundle/Strategy/AmocWestStrategy.php
- src/InloopBundle/Strategy/GebruikersruimteStrategy.php
- src/InloopBundle/Strategy/SpecificLocationStrategy.php
- src/InloopBundle/Strategy/ToegangOverigStrategy.php
- src/InloopBundle/Strategy/VillaWesterweideStrategy.php
- src/InloopBundle/Strategy/WinteropvangEUBurgers.php
Paar fixes in `AccessUpdater`:
- Query in `SpecificLocationStrategy` moet denk ik zijn `AND :locatie IN specifiekeLocaties`, niet `AND specifiekeLocaties IN (:locaties)`, want parameter `:locaties` is hier precies 1 locatie, niet een collectie.
- Constructor arg van `SpecificLocationStrategy` werd niet gebruikt, dus heb ik verwijderd.
- Namespace van drie `Strategy`'s klopte niet (`App\InloopBundle\Strategy` ipv `InloopBundle\Strategy`)
> Fix access updater

- config/packages/test/liip_fixtures.yaml
- config/services/clip/services.yaml
- config/services/hs/services.yaml
- config/services/oek/services.yaml
- fixtures/app.yaml
- fixtures/inloop.yaml
- src/ClipBundle/Event/PostcodeSubscriber.php
- src/HsBundle/Event/DienstenLookupSubscriber.php
- src/HsBundle/Event/FactuurSubscriber.php
- src/HsBundle/Event/KlantUpdater.php
- src/InloopBundle/Service/AccessUpdater.php
- src/InloopBundle/Strategy/SpecificLocationStrategy.php
- src/InloopBundle/Strategy/ToegangOverigStrategy.php
- src/InloopBundle/Strategy/WinteropvangEUBurgersStrategy.php
- src/OekBundle/Event/DeelnemerEventSubscriber.php
- templates/inloop/opmerkingen/index.html.twig
- tests/InloopBundle/Service/AccessUpdaterTest.php
- tests/InloopBundle/Strategy/SpecificLocationStrategyTest.php
- tests/InloopBundle/Strategy/WinteropvangEUBurgersStrategyTest.php
- tests/bootstrap.php
AccessUpdater en twee strategieen werkten niet goed. De tests daarvoor geupdate
Maar tests werken ook niet goed.
Daarnaast probleem met inloop opmerkingen route die niet meer bestond (en niet goed werkte) En een HomeService probleem met Events waardoor het saldo neit goed werd berekend.
> Patches for release 2.6.15

- templates/inloop/schorsingen/view.nl.pdf.twig
> Telefoonnummer aangepast in de NL brief. Engels stond al goed.

- config/packages/twig.yaml
- fixtures/mw.yaml
- templates/mw/form.html.twig
@jtborger Dank voor de tip, met `column-count: 2` was het heel eenvoudig.
> Resultaat-checkboxes in twee kolommen #1619

- templates/klant_basis.html.twig
@jtborger Er zat nog een foutje in de partial templates.
> Fix partial templates #1502

- src/IzBundle/Filter/IzKlantFilter.php
- src/IzBundle/Service/KlantDao.php
- tests/IzBundle/Filter/IzKlantFilterTest.php
> Filter "Ooit actief" ook toepassen op medewerker hulpvraag #980

- src/DagbestedingBundle/Entity/Intakeverslag.php
> Witregel intakeverslag #1634

- config/services/app/services.yaml
- config/services/ga/services.yaml
- config/services/inloop/services.yaml
- config/services/iz/services.yaml
- config/services/oek/services.yaml
- src/AppBundle/Controller/VrijwilligersController.php
- src/AppBundle/Event/AbstractDienstenVrijwilligerLookupSubscriber.php
- src/AppBundle/Event/DienstenVrijwilligerLookupEvent.php
- src/AppBundle/Event/DienstenVrijwilligerLookupSubscriber.php
- src/AppBundle/Event/Events.php
- src/GaBundle/Event/DienstenVrijwilligerLookupSubscriber.php
- src/InloopBundle/Event/DienstenVrijwilligerLookupSubscriber.php
- src/IzBundle/Event/DienstenVrijwilligerLookupSubscriber.php
- src/OekBundle/Event/DienstenVrijwilligerLookupSubscriber.php
- templates/app/vrijwilligers/_contactgegevens.html.twig
- templates/app/vrijwilligers/_diensten.html.twig
- templates/app/vrijwilligers/_documenten.html.twig
- templates/app/vrijwilligers/_persoonsgegevens.html.twig
- templates/app/vrijwilligers/view.html.twig
- templates/vrijwilliger_basis.html.twig
> Diensten toevoegen voor vrijwillgers #914

- templates/mw/klanten/view.html.twig
> Tab "Laatste registraties" toevoegen #1704

- src/InloopBundle/Controller/RegistratiesController.php
- src/InloopBundle/Filter/KlantFilter.php
- src/InloopBundle/Service/KlantDao.php
Je bedoelde toch bij registraties dat als iemand ingecheckt wordt hij niet meer in de lijst staat (want hij is al binnen)?
Fixes #1282
> Mensen die al binnen zijn niet in registratielijst tonen #1282

- docker-compose.yml
- docker/php/Dockerfile
- docker/php/xdebug.ini
Ik heb het teruggezet zoals eht stond en toen werkte het wel weer. We moeten even samen kijken naar een oplossing die voor ons beiden werkt, deze PR even om evt samen aan te werken of te overleggen.
> Inline debuggen werkte niet meer. 

- config/packages/parameters.yaml
- config/services/app/services.yaml
- config/services/inloop/services.yaml
- fixtures/app.yaml
- fixtures/inloop.yaml
- src/AppBundle/Controller/KlantenController.php
- src/AppBundle/Entity/Klant.php
- src/AppBundle/Form/KlantMergeType.php
- src/AppBundle/Form/KlantType.php
- src/AppBundle/Twig/AppExtension.php
- src/InloopBundle/Controller/IntakesController.php
- src/InloopBundle/Controller/KlantenController.php
- src/InloopBundle/Controller/RegistratiesController.php
- src/InloopBundle/Entity/Locatie.php
- src/InloopBundle/Form/KlantType.php
- src/OekraineBundle/Controller/BezoekersController.php
- templates/app/admin/klanten/merge.html.twig
- templates/app/klanten/_form.html.twig
- templates/app/klanten/_persoonsgegevens.html.twig
- templates/app/klanten/add.html.twig
- templates/inloop/intakes/_form_scripts.html.twig
- templates/inloop/intakes/aanmelding.txt.twig
- templates/inloop/klanten/add.html.twig
- templates/inloop/registraties/_active.html.twig
- templates/inloop/registraties/_history.html.twig
- templates/oekraine/bezoekers/add.html.twig
- templates/oekraine/intakes/aanmelding.txt.twig
- tests/AppBundle/Twig/AppExtensionTest.php
> Alles mbt TBC eruit #1679

- src/AppBundle/Controller/AbstractController.php
- src/HsBundle/Controller/DeclaratiesController.php
- src/HsBundle/Controller/RegistratiesController.php
- src/InloopBundle/Controller/LocatiesController.php
- src/OekBundle/Controller/TrainingenController.php
- src/ScipBundle/Controller/VerslagenController.php
Ik doe na aanmaken een redirect naar de view-action, daar staan de locatietijden. [Dit](https://github.com/deregenboog/ecd/pull/1763/files#diff-a4a1043bb6deda65148bae1e35e9fa2823921e76a7917cc47b8c942a7158ccffR29) is de relevante wijziging, de rest is wat opschoonwerk.
fixes #1515
> Na aanmaken locatie naar locatietijden #1515

- src/IzBundle/Event/DienstenLookupSubscriber.php
- src/MwBundle/Event/DienstenLookupSubscriber.php
- tests/IzBundle/Event/DienstenLookupSubscriberTest.php
> Contactpersoon bij diensten voor MW en IZ #993

- templates/app/klanten/_contactgegevens.html.twig
- templates/vrijwilliger_basis.html.twig
> Geen post/email rood #968

- src/InloopBundle/Entity/Schorsing.php
> Schorsing einddatum >= vandaag #974

- config/services/app/daos.yaml
- config/services/app/services.yaml
- src/AppBundle/DependencyInjection/Compiler/ReportsCompilerPass.php
- src/AppBundle/Entity/Doelstelling.php
- src/AppBundle/Export/GenericExport.php
- src/AppBundle/Form/DoelstellingType.php
- src/AppBundle/Service/DoelstellingDao.php
- src/Kernel.php
- templates/app/doelstellingen/index.html.twig
@jtborger Ik wilde de `ReportsCompilerPass` hernoemen, maar zag dat hij voor de doelstellingen eigenlijk niet nodig was. Doelstellingen werken nu simpelweg met een `!tagged_iterator`. Daardoor dekt de naam `ReportsCompilerPass` de lading weer, dus heb ik het zo gelaten. Wel zag ik dat de doelstellingen niet werkten, dus heb ik die ook even gefixt. Je moet maar even kijken of dit zo goed is allemaal.
fixes #1658
> Fix doelstellingen #1658

- config/services/oek/services.yaml
- src/OekBundle/Report/DeelnemersPerTrainingGroep.php
- src/OekBundle/Report/DeelnemersPerTrainingStatus.php
@jtborger Dit rapport vraagt eigenlijk dezelfde data als rapport "Deelnemers per naam training en groep". Daarom heb ik die als base-class gebruikt en alleen de data geherstructureerd om dit rapport te maken. Volgens mij klopt het zo, maar je moet maar even kijken of je het hiermee eens bent.
fixes #1378
> Rapport toevoegen (deelnemers per training en status) #1378

- assets/js/app.js
- src/AppBundle/Form/RapportageType.php
> Add select-all and select-none to multi-select fields #1574

- src/AppBundle/Model/Dienst.php
- src/InloopBundle/Event/DienstenLookupSubscriber.php
- templates/app/klanten/_diensten.html.twig
- templates/app/vrijwilligers/_diensten.html.twig
Inloophuizen worden nu niet meer opgesomd, maar simpelweg "open dossier". Voor de gebruikersruimtes heb ik niks veranderd. Had dat ook "open dossier" moeten worden ipv opsomming ruimtes?
fixes #1524
> Open dossier ipv opsomming inloophuizen #1524

- assets/js/app.js
- docker-compose.yml
- src/AppBundle/Form/RapportageType.php
- yarn.lock
> Select all/none standaard disabled #1574

- fixtures/mw.yaml
- src/InloopBundle/Controller/VerslagenController.php
Verslagen gemaakt vanuit inloop voor klanten die geen MW dossier hebben krijgen nu automatisch een MW dossier met een default project (AMW).
> Fixes #1737 and #1722.

- fixtures/app.yaml
- fixtures/oekraine.yaml
- fixtures/villa.yaml
- src/AppBundle/Form/MedewerkerSelectType.php
- src/OekraineBundle/Entity/Inkomen.php
- src/OekraineBundle/Entity/Intake.php
- src/OekraineBundle/Form/BezoekerType.php
- templates/base-2-col.html.twig
- templates/base.html.twig
Fixtures voor Oekraine gemaakt.
Gezorgd dat de form_theme overrides in form/app.twig.html nu ook standaard meegenomen worden door ze mee te nemen in base.html.twig
> Oekraine mental coach aanpassingen

- src/AppBundle/Controller/KlantenController.php
- src/AppBundle/Controller/VrijwilligersController.php
- templates/app/klanten/_documenten.html.twig
- templates/vrijwilliger_basis.html.twig
Rechten aangepast van ROLE_ADMIN naar ROLE_SECRETARIAAT zodat medewerker bestanden van Klant en Vrijwilliger (VOG en vw-overeenkomst) kunnen verwijderen
> Fixes #1876 rechten aangepast verwijderen docs

- src/TwBundle/Controller/CoordinatorenController.php
Fixed #1861 
Er was een kleine bug bij het openen van de entiteit in de sjabloon. Ik heb het opgelost in CoordinatorenController. Nu wordt de waarde correct weergegeven in de sjabloon. En de verwijderfout is opgelost.
> #1861 fixed entity error in template

- config/services/ga/daos.yaml
- fixtures/ga.yaml
- migrations/2025/Version20250128100704.php
- src/GaBundle/Entity/Groep.php
- src/GaBundle/Entity/GroepBuurtrestaurants.php
- tests/GaBundle/Controller/GroepenControllerTest.php
#1889 
> Ik heb dat gefixd. Ik heb een migratie gemaakt om de groepentabel bij te werken en OpenHuis om te zetten naar Buurtrestaurants. Ik heb ook de relevante tags en klassen/fixtures gewijzigd. Vervolg van dit #1891 
ik heb dat groep_buurtrestaurants gefixt met clein letters
> #1889 openhuis naar groepsactiviteiten 2

- src/AppBundle/Controller/NationaliteitenController.php
- src/AppBundle/Controller/TalenController.php
- src/AppBundle/Entity/Taal.php
- src/AppBundle/Filter/NationaliteitFilter.php
- src/AppBundle/Filter/TaalFilter.php
- src/AppBundle/Form/NationaliteitFilterType.php
- src/AppBundle/Form/NationaliteitType.php
- src/AppBundle/Form/TaalFilterType.php
- src/AppBundle/Form/TaalType.php
- src/AppBundle/Service/NationaliteitDao.php
- src/AppBundle/Service/NationaliteitDaoInterface.php
- src/AppBundle/Service/TaalDao.php
- src/AppBundle/Service/TaalDaoInterface.php
- templates/app/nationaliteiten/index.html.twig
- templates/app/talen/index.html.twig
- templates/navigation.html.twig
#1501  Ik heb de nodige ontwikkelingen gedaan voor het toevoegen, verwijderen, bewerken en filteren van de pagina's voor nationaliteit en taal. Hierdoor kunnen beheerders nu toegang krijgen tot deze tabellen, ze doorzoeken en aanpassen.
> #1501 nationaliteit taal 3

- migrations/2025/Version20250204134730.php
- src/OekBundle/Entity/Groep.php
- src/OekBundle/Form/GroepType.php
- src/OekBundle/Form/LidmaatschapType.php
- src/OekBundle/Form/TrainingType.php
- templates/oek/groepen/index.html.twig
- templates/oek/groepen/view.html.twig
#1381 #1908 
Hi @jtborger Ik heb die gefixt bij ActivatableTrial. nu gelof Ik dat beter is :)
> #1381 actife groepen oek 2

- config/services/villa/reports.yaml
- src/VillaBundle/Report/OverzichtSlapers.php
- src/VillaBundle/Report/Slapers.php
- src/VillaBundle/Service/SlaperDao.php
Tevens de transformType functie vereenvoudigd.
> Overzicht slapers toegevoegd

- templates/dagbesteding/deelnemers/view.html.twig
- templates/dagbesteding/projectplan/_list.html.twig
- templates/dagbesteding/projectplan/delete.html.twig
- templates/dagbesteding/verslagen/_list.html.twig
#1635 Hi Jan. ik heb alleen een nieuwe tabje toegevogt en ik heb dat Projectpan genoemd. en dan lat ik de Intakeverslag verslagen in die tabje te zien.
over label van Projectpan ben ik niet zeker. alstjebliefd lat me veranderen als het niet geod is. 
ik heb het gedaan door een niewuwe template en geen php functions, viend jij dat genoeg is?
> #1635 Added new tab for projectplan (Intakeverslag) in dagbesteding

- config/services/tw/exports.yaml
#1872 
Hi Jan, het naamveld van klanten in het exportbestand van de Koppelingen-tabel is gefixt.
> Fixed koppelingen export name field

- src/TwBundle/Filter/VerhuurderFilter.php
- src/TwBundle/Service/VerhuurderDao.php
- tests/TwBundle/Filter/VerhuurderFilterTest.php
fixes #1789 
Hi @jtborger 
Dit Pull Request heeft betrekking op het probleem met de unit test in nummer #1905 .
Ik heb het PHPunit-probleem opgelost omdat de sql query eerder was gewijzigd, waardoor de test faalde.
> #1789 verhuurder filter gekoppeld 2

- src/TwBundle/Filter/VerhuurderFilter.php
- src/TwBundle/Service/VerhuurderDao.php
#1789 
I tried refactoring the code of filtering by gekoppeld field.
So we have it by doctrine functionality. also it works well in Locally. it is a complexes process which most check difference variables. please test it with real data on live.
> #1789 Fixed filter by gekoppeld in verhuurder (TW) - REFACTORE

- config/services/villa/exports.yaml
- config/services/villa/services.yaml
- src/VillaBundle/Controller/LogeerOpvangController.php
- templates/navigation.html.twig
- templates/villa/logeer_opvang/close.html.twig
- templates/villa/logeer_opvang/index.html.twig
- templates/villa/logeer_opvang/open.html.twig
- templates/villa/logeer_opvang/view.html.twig
- templates/villa/subnavigation.html.twig
Hi @jtborger Ik heb alle conflicten van #1878-logeertype-toevoegen-2 opgelost, en ik heb dat getest die werk wel.
dat mag mergen nu
#1903 #1878
> #1878 logeertype toevoegen 2

- config/services/villa/exports.yaml
- config/services/villa/services.yaml
- src/VillaBundle/Controller/LogeerOpvangController.php
- templates/navigation.html.twig
- templates/villa/logeer_opvang/close.html.twig
- templates/villa/logeer_opvang/index.html.twig
- templates/villa/logeer_opvang/open.html.twig
- templates/villa/logeer_opvang/view.html.twig
- templates/villa/subnavigation.html.twig
Tabbladen toegevoegd voor logeertypen
> #1878 logeertype toevoegen

- config/packages/roles_drg.yaml
- config/packages/security.yaml
- config/packages/web_profiler.yaml
- fixtures/app.yaml
- templates/navigation.html.twig
Ik heb een nieuwe rol aangemaakt: "ROLE_CLIP_ALLEEN_CLIENTEN". Met deze rol kun je alleen de tab Clienten gebruiken (in Clip paginas).
> #1685 cleinten toegang 2

- src/DagbestedingBundle/Controller/DeelnemersController.php
- src/DagbestedingBundle/Entity/Deelnemer.php
- src/DagbestedingBundle/Form/DeelnemerCloseType.php
Hi, @jtborger ik heb de typo gefixed.
#1874 , #1921 
trijecten ---> trajecten
> #1874 auto traject sluiten 3

- fixtures/uhk.yaml
- migrations/2025/Version20250314100918.php
- src/UhkBundle/Controller/DeelnemersController.php
- src/UhkBundle/Controller/ProjectenController.php
- src/UhkBundle/Entity/Deelnemer.php
- src/UhkBundle/Entity/Project.php
- src/UhkBundle/Filter/DeelnemerFilter.php
- src/UhkBundle/Form/DeelnemerFilterType.php
- src/UhkBundle/Form/DeelnemerType.php
- src/UhkBundle/Form/ProjectSelectType.php
- src/UhkBundle/Form/ProjectType.php
- src/UhkBundle/Service/DeelnemerDao.php
- src/UhkBundle/Service/ProjectDao.php
- src/UhkBundle/Service/ProjectDaoInterface.php
- templates/uhk/deelnemers/index.html.twig
- templates/uhk/deelnemers/view.html.twig
- templates/uhk/projecten/add.html.twig
- templates/uhk/projecten/delete.html.twig
- templates/uhk/projecten/edit.html.twig
- templates/uhk/projecten/index.html.twig
- templates/uhk/subnavigation.html.twig
@jtborger 
Ik heb een tabel voor Projecten aangemaakt met een kleurveld voor Deelnemers en de bijbehorende filters gemaakt. Op dit moment kan elke Deelnemer maar één Project kiezen, maar in de toekomst kan ik dit eenvoudig aanpassen zodat meerdere projecten per Deelnemer mogelijk zijn met een paar codewijzigingen. Ik heb ook mock-projecten toegevoegd in de Fixture.
> Fixed #1786 Added project with color options for deelnemer in Uhk

- assets/js/calendar/index.js
- src/VillaBundle/Controller/OvernachtingenController.php
- src/VillaBundle/Entity/Slaper.php
- templates/edit.ajax.html.twig
- templates/villa/_edit.ajax.html.twig
- templates/villa/slapers/view.html.twig
Melding voor onvernachtingen toegevoegd aan de overzicht tab voor overnachtingen
> #1904 melding saldo slapers 5

- assets/js/calendar/index.js
- src/VillaBundle/Controller/OvernachtingenController.php
- templates/edit.ajax.html.twig
- templates/villa/_edit.ajax.html.twig
Meldingen toegevoegd in de modal bij een boeking van een nacht.
Afhankelijk van de hoeveelheid beschikbare nachten wordt de corresponderende melding weergegeven.
> #1904 melding saldo slapers 3

- assets/js/calendar/index.js
- config/services/iz/daos.yaml
- config/services/iz/services.yaml
- migrations/2025/Version20250325154516.php
- src/IzBundle/Controller/DeelnamesController.php
- src/IzBundle/Controller/TrainingenController.php
- src/IzBundle/Entity/Deelname.php
- src/IzBundle/Entity/IzVrijwilliger.php
- src/IzBundle/Entity/Training.php
- src/IzBundle/Form/DeelnameType.php
- src/IzBundle/Form/TrainingType.php
- src/IzBundle/Service/DeelnameDao.php
- src/IzBundle/Service/DeelnameDaoInterface.php
- src/IzBundle/Service/TrainingDao.php
- src/IzBundle/Service/TrainingDaoInterface.php
- src/VillaBundle/Controller/OvernachtingenController.php
- templates/edit.ajax.html.twig
- templates/iz/deelnames/_list.html.twig
- templates/iz/deelnames/add.html.twig
- templates/iz/deelnames/delete.html.twig
- templates/iz/deelnames/edit.html.twig
- templates/iz/subnavigation.html.twig
- templates/iz/trainingen/index.html.twig
- templates/iz/trainingen/view.html.twig
- templates/iz/vrijwilligers/_tabs.html.twig
- templates/iz/vrijwilligers/view.html.twig
- templates/villa/_edit.ajax.html.twig
Trainingen functionaliteit toegevoegd aan IZ ( Informele Zorg )
> #1865 add training iz 2

- config/packages/framework.yaml
- config/packages/roles_drg.yaml
- src/AppBundle/Controller/ErrorController.php
- templates/navigation.html.twig
- templates/security/access_denied.html.twig
uitfaseren van controller_app_klanten en controller_app_vrijwilligers met custom foutmelding bij access van de rollen die hier de uitgefaseerde rollen hebben. Issue opgelost met teveel rechten toewijzen door subrol.
> #1480 uitfaseren klanten vrijwilligers lijsten 4

- assets/js/inloop/registraties/active.js
- config/packages/web_profiler.yaml
- templates/inloop/registraties/_active.html.twig
- templates/inloop/registraties/_history.html.twig
- templates/inloop/registraties/group_action/_active.html.twig
- templates/inloop/registraties/group_action/_history.html.twig
#1510 
Hoi @jtborger ,
Ik heb een sectie aan de template toegevoegd om de mogelijkheid van batchverwerking via AJAX voor de Bezoekersregistratie-tabel (Nu binnen en Recent uitgecheckt) mogelijk te maken.
Alles is ontwikkeld met jQuery, en ik heb gebruik gemaakt van eerdere AJAX-functionaliteiten.
> #1510 batch verwerking bezoekersregistratie

- src/AppBundle/Command/RunSqlCommand.php
- src/InloopBundle/Resources/sql/management_report_views.sql
Mogelijke betere oplossing voro de management report views.
> Betere logginig in runSql commando.

- src/AppBundle/Command/RunSqlCommand.php
- src/InloopBundle/Resources/sql/management_report_views.sql
IGNORE weggehald in create table statement om warnings te krijgen waarom die tabel neit wordt aangemaakt.
> RunSql aangepast voor betere logging en debugging.

- src/AppBundle/Controller/AbstractController.php
- src/UhkBundle/Controller/ProjectenController.php
- src/UhkBundle/Service/DeelnemerDao.php
- src/UhkBundle/Service/DeelnemerDaoInterface.php
- templates/uhk/projecten/index.html.twig
Fixes #1954 Ik heb een verwijderen functie gemaakt voor projecten zonder deelnemers. Voor projecten die al deelnemers hebben, geeft het een foutmelding.
> fixes #1954 Added delete function for free projects for UHK

- src/TwBundle/Filter/VerhuurderFilter.php
- tests/TwBundle/Filter/VerhuurderFilterTest.php
Hi @jtborger 
Ik keek weer naar issue #1760. Met mijn aanpassing en mijn lokale data werkt het.
> Fixes #1760 fixed query of filtering Klanten for Verhuurders
